### ISSUE TITLE
Shouldn't ifconfig be removed ?

### ISSUE THREAD

**Issue by mbennehar** [pschmitt/pia-tools#10]
The net-tools package which provide ifconfig is deprecated, shouldn't it be replaced by another tools ? Let's say 'ip addre' for instance ?

**Comment by pschmitt** [comment]
There hasn't been any more feedback. I'll commit the change.

**Comment by angelic-sedition** [comment]
I prefer the previous behaviour where it would add rules for all interfaces not just whatever is in use. How about something like the following?
```
ip link show up | awk -v ORS="" -F ":" '/^[0-9]/ && !/lo/ {print $2}' | sed 's/^ //'
```
This will work with the for loops for allowing/denying multiple interfaces that are still in there. For just the interface in use you could use a /state UP/ instead, but I still think it would be better to add all interfaces like before.
