### ISSUE TITLE
How to use on Ubuntu

### ISSUE THREAD

**Issue by mattfox27** [pschmitt/pia-tools#2]
How can i use this on ubuntu?  I have installed and ran setup but how can i start it?

**Comment by alexbooker** [comment]
What is the status of this now, do you know?

**Comment by pschmitt** [comment]
15.04+ is using systemd.

**Comment by alexbooker** [comment]
![](http://i.imgur.com/WMBF2XK.png)

Awesome!

I am going to try this script out soon.

**Comment by alexbooker** [comment]
Works fine on Ubuntu Gnome 15.04.
