### ISSUE TITLE
"Updating configuration... unzip:  cannot find or open , .zip or .ZIP."

### ISSUE THREAD

**Issue by jhoward321** [pschmitt/pia-tools#34]
When running pia-tools --setup, the script fails while trying to unzip the configuration files on Fedora 24. Might be a specific issue with Fedora, but I think it should be a simple fix in the unzip portion of update_config()

**Comment by hhansx** [comment]
Same issue on raspbian

**Comment by Uncleleech** [comment]
I fixed this by just changing the absolute path when it runs the unzip.

Not sure what that command is doing exactly tbh but I got the program running.

**Comment by lknows** [comment]
@Uncleleech Could you explain how you did this?

**Comment by Uncleleech** [comment]
@lknows I just changed the the line to the /etc/openvpn/<blah<.zip

**Comment by efronberlian** [comment]
I am not sure what the $overwrite variable is supposed to do, but without it, the unzip works fine.

At this line:

> unzip "$overwrite" -d "$PIA_CONFIG_DIR" -q "$PIA_CONFIG_DIR/openvpn.zip"

change it to:

unzip -d "$PIA_CONFIG_DIR" -q "$PIA_CONFIG_DIR/openvpn.zip"
