### ISSUE TITLE
dynamically add a firewall rule

### ISSUE THREAD

**Issue by splifter** [pschmitt/pia-tools#38]
The description of the repo says:
> ..., dynamically add a firewall rule.

Is this applying just for transmission? I hoped i could set easily a firewall rule to route incoming ssh connection via eth0, my "normal" public ip?
If so, could you please explain how. I wasn't able to figure it out while reading the code.

Thank you!

**Comment by pschmitt** [comment]
Yeah

**Comment by pschmitt** [comment]
The "dynamic firewall rule" refers to the `-a` and `-d` switches.

- https://github.com/pschmitt/pia-tools/blob/master/pia-tools#L59
- https://github.com/pschmitt/pia-tools/blob/master/pia-tools#L60
